apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    rbac.authorization.k8s.io/aggregate-to-poweruser: "true"
  name: fabricgateways-poweruser
rules:
- apiGroups:
  - zalando.org
  resources:
  - fabricgateways
  verbs:
  - create
  - update
  - patch
  - delete
  - deletecollection
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    rbac.authorization.k8s.io/aggregate-to-readonly: "true"
  name: fabricgateways-readonly
rules:
- apiGroups:
  - zalando.org
  resources:
  - fabricgateways
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    rbac.authorization.k8s.io/aggregate-to-poweruser: "true"
  name: fabriceventstreams-poweruser
rules:
- apiGroups:
  - zalando.org
  resources:
  - fabriceventstreams
  verbs:
  - create
  - update
  - patch
  - delete
  - deletecollection
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    rbac.authorization.k8s.io/aggregate-to-readonly: "true"
  name: fabriceventstreams-readonly
rules:
- apiGroups:
  - zalando.org
  resources:
  - fabriceventstreams
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    rbac.authorization.k8s.io/aggregate-to-poweruser: "true"
  name: servicelevelobjectives-poweruser
rules:
- apiGroups:
  - zalando.org
  resources:
  - servicelevelobjectives
  verbs:
  - create
  - update
  - patch
  - delete
  - deletecollection
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    rbac.authorization.k8s.io/aggregate-to-readonly: "true"
  name: servicelevelobjectives-readonly
rules:
- apiGroups:
  - zalando.org
  resources:
  - servicelevelobjectives
  verbs:
  - get
  - list
  - watch